### ISSUE TITLE
[EngAut] generate prdoc ui PoC

### ISSUE THREAD

**Issue by mordamax** [paritytech/command-bot#244]
Related discussion: https://forum.parity.io/t/pr-documentation-prdoc/2065/21

In the future the prdocs will be a part of CI which will block PR unless either 1) the prdoc file for PR is provided 2) PR has the label `R0-silent`

But for this to happen - we need to improve the devX by providing a simpler way to provide documentation for PR

The idea was - if the CI detected that prdoc was missing - send a link to some UI, which would provide an easier way to tell what was the change in PR and to whom this change relates. UI could enhance devX by providing the fields with an explanation and examples of how to document PR and what the audiences are etc

Obstacles: command-bot does not provide UI for now (tbd https://github.com/paritytech/command-bot/issues/128)

**Comment by mutantcornholio** [comment]
I'm thinking that this could be a static GitHub-pages UI, and even a part of [prdoc](https://github.com/paritytech/prdoc) repo itself.  
I'll try to make a PoC for it

https://forum.parity.io/t/pr-documentation-prdoc/2065/25?u=yuri_volkov

**Comment by chevdor** [comment]
Beware, in the first version, we had ONE schema.
I am working on a new version where the schema will be confirgurable, per repo, and stored in the repo.
So `prdoc` will no longer have information about a specific schema in its repo (a schema will remain but will be used for testing mainly).

**Comment by mutantcornholio** [comment]
And just when I was ready to test it, I found out that GitHub OAuth API doesn't support CORS: https://github.com/isaacs/github/issues/330.  
After some research it seems that it's actually impossible to create a clientside-only app, that would use GitHub API.  
Seems that we would need a server just to keep client_secret and do key exchange.

**Comment by mutantcornholio** [comment]
@chevdor Hi! Here's an option how that could look: https://mutantcornholio.github.io/prdoc/?pull=16&org=paritytech&repo=prdoc&branch=wk-231019-completions
If you click "Submit", it'll take you to a link [like this](https://github.com/paritytech/prdoc/new/wk-231019-completions?filename=prdoc%2Fpr_16.prdoc&value=---%0Adoc%3A%0A%20%20-%20notes%3A%0A%20%20%20%20%20%20%5B%5D%0A%20%20%20%20audience%3A%20Node%20Operator%0A%20%20%20%20description%3A%20Some%20actions%20required%0Acrates%3A%0A%20%20%5B%5D%0Amigrations%3A%0A%20%20db%3A%0A%20%20%20%20%5B%5D%0A%20%20runtime%3A%0A%20%20%20%20%5B%5D%0Ahost_functions%3A%0A%20%20%5B%5D%0Atitle%3A%20Alternative%20title%0Aauthors%3A%0A%20%20-%20mutantcornholio%0A), which would add a file to your repository. 

I've pushed the source code [here](https://github.com/paritytech/prdoc/tree/yuri/prdoc-gen-poc), however, this is a PoC, so it's not something that's remotely ready for merge.
Some of the questions that are yet to be resolved / work to be done:
* `prdoc` utility supports templating, while this tool currently just does `yaml.stringify`, which produces less readable results
* I had to do some changes in the schema, in order to adapt it to [uniforms](https://uniforms.tools/). The changes kinda make sense, but I haven't tested `prdoc` utility with them yet
* There's the question of generating of links for the ui, and I would probably put it to [check-prdoc.yml](https://github.com/paritytech/polkadot-sdk/blob/master/.github/workflows/check-prdoc.yml). Maybe make it reusable.

**Comment by chevdor** [comment]
Woo that looks like a neat option !
You made a copy of a the schema, so I don't see the diff easily since upstream has changed.
Could you update to the current schema ? It is the one added to the SDK repo in https://github.com/paritytech/polkadot-sdk/pull/1946

**Comment by mutantcornholio** [comment]
https://github.com/paritytech/prdoc/compare/yuri/prdoc-gen-poc?expand=1#diff-013e70c9bc6c6ea9370d573976ee48fd49cf49142968700bdb9b37a48d105c27
Here are the changes for the schema in `prdoc`, I'll try to adapt polkadot's new one a bit later

**Comment by mutantcornholio** [comment]
Most of the reasons were cutting corners, to get PoC working.  
After googling for a bit, I already managed to fix `version` and `$schema`, but `audience` may be not so simple. If we want to go with the idea, I can experiment a bit more on this.
