### ISSUE TITLE
Default artifacts handling is wrong

### ISSUE THREAD

**Issue by TriplEight** [paritytech/command-bot#75]
https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/1606454

`WARNING: Part of .git directory is on the list of files to archive`

**Comment by mordamax** [comment]
@TriplEight is it still the issue?
if yes - how to reproduce?
thanks!

**Comment by joao-paulo-parity** [comment]
@TriplEight We create the artifacts folder in `.git` because `.git` is invariably ignored by default for every Git project regardless of `.gitignore`. There's no point in creating the folder in the project directly because it's more error-prone (might clash or have weird repercurssions for whatever reason) and it would complicate scripts which deal with git commits e.g. https://github.com/paritytech/pipeline-scripts/blob/294a98d4fbdbc2daf38b4d5e8da89735a7cb7d53/bench-bot.sh#L139.

The warning is irrelevant to us because putting the artifacts folder in `.git` is intended and has no bad side-effects. Saying "it's wrong" needs more elaboration on why it's wrong.

Feel free to reopen in case you insist on getting rid of the warning.
